version: '2.1'
services:
    jupyter:
        build:
            context: .
        volumes:
            - ./src/widgets:/home/jovyan/widgets
            - ./src/notebooks:/home/jovyan/notebooks
            - ./src/ext:/home/jovyan/ext
            # - ./src/code-snippets:/home/jovyan/.local/share/jupyter/metadata/code-snippets/
        ports:
            - "8888:8888"
        environment:
            NB_UID: ${UID}
            NB_GID: ${GID}
        entrypoint: start-notebook.sh
        command: --VoilaConfiguration.enable_nbextensions=True --LabApp.token='' --watch