version: '2.1'
services:
    jupyter:
        build:
            context: .
        volumes:
            - ./src:/home/jovyan
        ports:
            - "8888:8888"
        environment:
            NB_UID: ${UID}
            NB_GID: ${GID}