version: "2.1"
services:
  jupyter:
    build:
      context: .
    volumes:
      - ./widgets:/home/jovyan/widgets
      - ./notebooks:/home/jovyan/notebooks
      - ./ext:/home/jovyan/ext
      # - ./src/code-snippets:/home/jovyan/.local/share/jupyter/metadata/code-snippets/
    ports:
      - "8888:8888"
    environment:
      NB_UID: ${UID}
      NB_GID: ${GID}
    entrypoint: start-notebook.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: --VoilaConfiguration.enable_nbextensions=True --LabApp.token=''
